//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusyBeasDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public int id { get; set; }
        public int userId { get; set; }
        public string street { get; set; }
        public string streetTwo { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public Nullable<System.DateTime> CREATE_TS { get; set; }
        public Nullable<System.DateTime> UPDATE_TS { get; set; }
    
        public virtual user user { get; set; }
    }
}
