//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusyBeasDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class serviceRequest
    {
        public int id { get; set; }
        public int userId { get; set; }
        public int serviceId { get; set; }
        public System.DateTime scheduledDate { get; set; }
        public Nullable<bool> fulfilled { get; set; }
        public Nullable<decimal> hoursTaken { get; set; }
    
        public virtual service service { get; set; }
        public virtual user user { get; set; }
    }
}
