//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusyBeasDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public service()
        {
            this.serviceRequests = new HashSet<serviceRequest>();
        }
    
        public int id { get; set; }
        public string serviceName { get; set; }
        public string serviceDescription { get; set; }
        public decimal pricePerHour { get; set; }
        public Nullable<System.DateTime> CREATE_TS { get; set; }
        public Nullable<System.DateTime> UPDATE_TS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<serviceRequest> serviceRequests { get; set; }
    }
}
